export const actionPermissionsConstant = {
  readAskersSearch: 'read:askers/search',
  readAskerDetail: 'read:asker/detail',
  readAskerSupportHistory: 'read:asker/support-history',
  writeAskerBlacklist: 'write:asker/blacklist',
  writeAskerChangeToTasker: 'write:asker/change-to-tasker',
  readAskerUserNote: 'read:asker/user-note',
  writeAskerUserNote: 'write:asker/user-note',
  readAskerTaskNote: 'read:asker/task-note',
  readAskerTaskHistory: 'read:asker/task-history',
  readAskerSchedules: 'read:asker/schedules',
  readAskerSubscription: 'read:asker/subscription',
  readAskerFavouriteTasker: 'read:asker/favourite-tasker',
  writeAskerFavouriteTasker: 'write:asker/favourite-tasker',
  readAskerTransaction: 'read:asker/transaction',
  readAskerOutstandingDebt: 'read:asker/outstanding-debt',
  readAskerBlacklistTasker: 'read:asker/blacklist-tasker',
  readAskerReward: 'read:asker/reward',
  readAskerPromotionHistory: 'read:asker/promotion-history',
  writeAskerFine: 'write:asker/fine',
  writeAskerCompensation: 'write:asker/compensation',
  writeAskerDelete: 'write:asker/delete',
  writeAskerOffer: 'write:asker/offer',
  writeAskerWithdraw: 'write:asker/withdraw',
  writeAskerDeposit: 'write:asker/deposit',
  writeAskerDisabledToActive: 'write:asker/change-disabled-to-active',
  readAskerComplaint: 'read:asker/complaint',

  writeAskerBlacklistTasker: 'write:asker/blacklist-tasker',
  readAskersSearchBlacklist: 'read:askers/search-blacklist',
  readAskersInactive: 'read:askers/inactive',
  readAskersBpayDebt: 'read:askers/bpay-debt',
  sendAskersBpayDebt: 'send:askers/bpay-debt',
  readAskersFeedback: 'read:askers/feedback',
  readAskersOutstandingDebt: 'read:askers/outstanding-debt',
  sendAskersOutstandingDebt: 'send:askers/outstanding-debt',
  readAskersDoneFirstTask: 'read:askers/done-first-task',
  sendAskersSurvey: 'send:askers/survey',
  writeAskersSurvey: 'write:askers/survey',
  readAskersSurvey: 'read:askers/survey',
  readTaskerSearch: 'read:tasker/search',
  readTaskerPremium: 'read:tasker/premium',
  readTaskerInfo: 'read:tasker/info',
  writeTaskerStatus: 'write:tasker/status',
  writeTaskerEdit: 'write:tasker/edit',
  writeTaskerPremium: 'write:tasker/premium',
  readTaskerNotes: 'read:tasker/notes',
  writeTaskerNotes: 'write:tasker/notes',
  readTaskerSupportHistory: 'read:tasker/support-history',
  writeTaskerDelete: 'write:tasker/delete',
  readTaskerToTheTask: 'read:tasker/search-tasker-to-the-task',
  readAskerHasLowRatingTask: 'read:asker/asker-has-low-rating-task',

  readTaskerServices: 'read:tasker/services',
  readTaskersByStatus: 'read:taskers/read-by-status',
  readTaskersBirthday: 'read:taskers/read-by-birthday',
  readTaskersReceiveMonthlyReward: 'read:taskers/receive-monthly-reward',
  readTaskersNoMonthlyReward: 'read:taskers/no-monthly-reward',
  readTaskersInactive: 'read:taskers/inactive',
  readTaskersLowBalance: 'read:taskers/low-balance',
  readTaskersByTaskDone: 'read:taskers/read-by-task-done',
  readTaskersOnboardingList: 'read:taskers/onboarding',
  readTaskersTopup: 'read:taskers/top-up',

  readTaskersWorkingTime: 'read:taskers/working-time',
  writeTaskerServices: 'write:tasker/services',
  readTaskerTaskHistory: 'read:tasker/task-history',
  readTaskerTodoTask: 'read:tasker/todo-task',
  readTaskerCalendar: 'read:tasker/calendar',
  readTaskerLockedHistory: 'read:tasker/locked-history',
  readTaskerLockedCancelTask: 'read:tasker/locked-cancel-task',
  readTaskerCancelTaskHistory: 'read:tasker/cancel-task-history',
  readTaskerFinanceTransaction: 'read:tasker/finance-transaction',
  readTaskerQuickPostedTask: 'read:tasker/quick-posted-task',
  readTaskerViewedTask: 'read:tasker/viewed-task',
  readTaskerCity: 'read:tasker/city',
  writeTaskerCity: 'write:tasker/city',
  WRITE_TASKER_BANK_ACCOUNT: 'write:tasker/bank-account',
  readTaskerReportSearch: 'read:tasker-report/search',
  readTaskerLowRatingSearch: 'read:tasker-low-rating/search',
  readTaskerRegisterSearch: 'read:tasker-register/search',
  readTaskerOpenAppHistory: 'read:tasker/open-app-history',
  readTaskerReferralHistory: 'read:tasker/referral-history',
  writeTaskerFine: 'write:tasker/fine',
  writeTaskerCompensation: 'write:tasker/compensation',
  readTaskerViolate: 'read:tasker/violate',
  writeTaskerViolate: 'write:tasker/violate',
  readTaskerTraining: 'read:tasker/training',
  writeTaskerTraining: 'write:tasker/training',
  readTaskerFavouritedAsker: 'read:tasker/favourited-asker',
  readTaskerQAList: 'read:tasker/qa-list',
  readTaskerLeakage: 'read:tasker/leakage',
  readTaskerTrainingQuizzes: 'read:tasker/training-quizzes',
  writeTaskerTrainingQuizzes: 'write:tasker/training-quizzes',

  readTaskerHaveTaskInDay: 'read:tasker-have-task-in-day/list',

  writeTaskerChangeToAsker: 'write:tasker/change-to-asker',
  readSettingSystem: 'read:settings/setting-system',
  writeSettingSystem: 'write:settings/setting-system',


  readTaskSchedulesSearch: 'read:task-schedules/search',
  readTaskScheduleDetail: 'read:task-schedule/detail',
  writeTaskScheduleStop: 'write:task-schedule/stop',
  writeTaskScheduleCancel: 'write:task-schedule/cancel',
  writeTaskScheduleActive: 'write:task-schedule/active',
  writeTaskScheduleUpdateTasker: 'write:task-schedule/update-tasker',
  writeTaskScheduleDetail: 'write:task-schedule/detail',
  writeTaskScheduleNote: 'write:schedule/note',
  readTaskSpecialListSearch: 'read:task-special-list/search',
  writeTaskSpecialListSearch: 'write:task-special-list/search',
  readTaskReportSearch: 'read:task-report/search',
  readTaskCanceledSearch: 'read:task-canceled/search',
  readSubscriptionSearch: 'read:subscription/search',
  sendSubscriptionSendOrderEmail: 'send:subscription/send-order-email',
  sendSubscriptionSendNotification: 'send:subscription/send-notification',
  sendSubscriptionSendReceipt: 'send:subscription/send-receipt',
  sendSubscriptionSendRenew: 'send:subscription/send-renew',
  readSubscriptionNote: 'read:subscription/note',
  writeSubscriptionNote: 'write:subscription/note',
  readSubscriptionDetail: 'read:subscription/detail',
  writeSubscriptionDetail: 'write:subscription/detail',
  writeSubscriptionCancel: 'write:subscription/cancel',
  writeSubscriptionRenew: 'write:subscription/renew',
  readSubscriptionTasker: 'read:subscription/tasker',
  writeSubscriptionTasker: 'write:subscription/tasker',
  readSubscriptionPurchaseOrder: 'read:subscription/purchase-order',
  writeSubscriptionPayPurchaseOrder: 'write:subscription/pay-purchase-order',

  readUserOtp: 'read:user-otp',
  writeNumberResentOtp: 'write:reset-number-resent-otp',
  call: 'call',
  writeTaskerDepositNewTasker: 'write:tasker/deposit-new-tasker',
  userManagement: 'user-management',
  teamManagement: 'team-management',

  // NOTIFICATION
  writeNotificationSendTasker: 'write:notification/send-tasker',
  writeNotificationSendAsker: 'read:notification/send-asker',
  readNotificationList: 'read:notification/list',
  readNotificationHistory: 'read:notification/history',
  writeNotificationCreate: 'write:notification/create',
  writeNotificationUpdate: 'write:notification/update',

  // COMPANY
  readCompany: 'read:company/list',
  writeCompanyCreate: 'write:company/create',
  writeCompanyUpdate: 'write:company/update',

  // STORE
  readGrocery: 'read:grocery/list',
  writeGroceryCreate: 'write:grocery/create',
  writeGroceryUpdate: 'write:grocery/update',

  // MARKETING
  readPromotion: 'read:promotion/list',
  readAskerPromotion: 'read:asker/promotion-list',
  writeSinglePromotion: 'write:promotion/create-single',
  writeSeriesPromotion: 'write:promotion/create-series',
  writeBRewards: 'write:promotion/create-brewards',
  writeCampaign: 'write:promotion/create-campaign',

  // GIFT INFO
  readGiftCategory: 'read:gift-info/list',
  writeGiftCategory: 'write:gift-info/write-category',

  // CHANGE BACKEND USER
  writeBackendUserCountry: 'write:backend-user/change-country',

  // ============================= ACCOUNTING =============================
  readPageAccounting: 'read:accounting',
  readBtaskeeEmployees: 'read:accounting/btaskeeEmployees',
  writeBtaskeeEmployees: 'write:accounting/btaskeeEmployees',
  readRefundTransaction: 'read:accounting/refund-transaction',
  writeOutstandingPaymentPay: 'write:accounting/outstanding-payment-pay',
  readReportDailyIncome: 'read:accounting/report-daily-income',
  writeTaskerWithdraw: 'write:tasker/withdraw',
  writeTaskerDeposit: 'write:tasker/deposit',
  readTaskerWithdraw: 'read:tasker/withdraw',
  readTaskerDeposit: 'read:tasker/deposit',
  readPayoutOfTasker: 'read:accounting/read-payout-of-tasker',
  writePayoutOfTasker: 'write:accounting/write-payout-of-tasker',
  writeRepayoutOfTasker: 'write:accounting/write-repayout-of-tasker',
  readAccountingSpendingMonthlyReport: 'read:accounting/read-spending-monthly-report',
  accountingCheckingExcel: 'accounting/checking-excel',
  accountingReadCardTransaction: 'accounting/read-card-transaction',
  accountingReadPaymentTransaction: 'accounting/read-payment-transaction',

  // ============================= TASK =============================
  readTaskSearch: 'read:task/search',
  readTaskGeneralInfo: 'read:task/general-info',
  writeTaskRequiredTools: 'write:task/required-tools',
  writeTaskSendNotification: 'write:task/send-notification',
  writeTaskSetCancelTask: 'write:task/set-cancel-task',
  writeTaskSetExpiredTask: 'write:task/set-expired-task',
  writeTaskSetDate: 'write:task/set-date',
  writeTaskSetDuration: 'write:task/set-duration',
  readTaskNote: 'read:task/note',
  readTaskViewedTasker: 'read:task/viewed-tasker',
  readTaskAcceptedTasker: 'read:task/accepted-tasker',
  readTaskConversation: 'read:task/conversation',
  readTaskSuportAskerTasker: 'read:task/suport-asker-tasker',
  readTaskRecommendTasker: 'read:task/recommend-tasker',
  readTaskCancelHistory: 'read:task/cancel-history',
  readTaskTaskerBlacklist: 'read:task/tasker-blacklist',
  writeTaskTaskerBlacklist: 'write:task/tasker-blacklist',
  readTaskChangesHistory: 'read:task/changes-history',
  writeTaskCreateSchedule: 'write:task/create-schedule',
  writeTaskCreateSubscription: 'write:task/create-subscription',
  writeTaskSupportAskerTasker: 'write:task/support-asker-tasker',
  writeTaskPromotion: 'write:task/promotion',
  readTaskPromotion: 'read:task/promotion',
  writeTaskNote: 'write:task/note',
  readTaskPaymentCardHistory: 'read:task/payment-card-history',
  writeTaskChangeAsker: 'write:task/write-task-change-asker',
  writeTaskFineAsker: 'write:task/fine-asker',
  writeTaskFineTasker: 'write:task/fine-tasker',
  readTaskCompensationList: 'read:task/compensation-list',
  readTaskPenaltyList: 'read:task/penalty-list',
  readTaskRefundRequest: 'read:task/refund',
  writeTaskRefundRequest: 'write:task/refund',
  writeTaskCreateRefundRequest: 'write:task/create-refund-request',
  writeTaskChangeToPosted: 'write:task/change-to-posted',
  sendTaskSendReceiptEmail: 'send:task/send-receipt-email',
  writeTaskSetAddress: 'write:task/set-address',
  writeTaskSetPaymentMethod: 'write:task/set-payment-method',
  writeTaskRating: 'write:task/rating',
  writeTaskAcceptTasker: 'write:task/accept-tasker',
  writeTaskDetail: 'write:task/update-task-detail',

  // ============================= REPORT =============================
  readReportTaskerActiveInDistrict: 'read:report/tasker-active-in-district',
  readReportLowRating: 'read:report/low-rating',
  readReportSupport: 'read:report/support',
  readReportSubscription: 'read:report/subscription',
  readReportOutstanding: 'read:report/outstanding',
  readReportTaskByDistrict: 'read:report/task-by-district',
  readReportUsagePromotion: 'read:report/usage-promotion',
  readReportBlacklistAsker: 'read:report/blacklist-asker',
  readReportSchedule: 'read:report/schedule',
  readReportRatingAsker: 'read:report/rating-asker',
  readReportPricing: 'read:report/pricing',
  readReportTaskByService: 'read:report/task-by-service',
  readReportCancelTask: 'read:report/cancel-task',
  readReportAskerReport: 'read:report/asker-report',
  readReportAskerInactive: 'read:report/asker-inactive',
  readReportSuspectTaskerReward: 'read:report/suspect-tasker-reward',
  readReportTaskStatistic: 'read:report/statistic-task',
  readReportTaskRating: 'read:report/task-rating',
  readTaskerOperationReport: 'read:tasker/operation-report',
  readTaskerGroupsManagementReport: 'read:tasker/groups-management-report',

  managerEmployee: 'manager-employee',

};

export const ACTION_PERMISSION_CONSTANTS = {
  readAskersSearch: 'read:askers/search',
  readAskerDetail: 'read:asker/detail',
  readAskerSupportHistory: 'read:asker/support-history',
  writeAskerBlacklist: 'write:asker/blacklist',
  writeAskerChangeToTasker: 'write:asker/change-to-tasker',
  readAskerUserNote: 'read:asker/user-note',
  writeAskerUserNote: 'write:asker/user-note',
  readAskerTaskNote: 'read:asker/task-note',
  readAskerTaskHistory: 'read:asker/task-history',
  readAskerSchedules: 'read:asker/schedules',
  readAskerSubscription: 'read:asker/subscription',
  readAskerFavouriteTasker: 'read:asker/favourite-tasker',
  writeAskerFavouriteTasker: 'write:asker/favourite-tasker',
  readAskerTransaction: 'read:asker/transaction',
  readAskerOutstandingDebt: 'read:asker/outstanding-debt',
  readAskerBlacklistTasker: 'read:asker/blacklist-tasker',
  readAskerReward: 'read:asker/reward',
  readAskerPromotionHistory: 'read:asker/promotion-history',
  writeAskerFine: 'write:asker/fine',
  writeAskerCompensation: 'write:asker/compensation',
  writeAskerDelete: 'write:asker/delete',
  writeAskerOffer: 'write:asker/offer',
  writeAskerWithdraw: 'write:asker/withdraw',
  writeAskerDeposit: 'write:asker/deposit',
  writeAskerDisabledToActive: 'write:asker/change-disabled-to-active',
  readAskerComplaint: 'read:asker/complaint',

  writeAskerBlacklistTasker: 'write:asker/blacklist-tasker',
  readAskersSearchBlacklist: 'read:askers/search-blacklist',
  readAskersInactive: 'read:askers/inactive',
  readAskersBpayDebt: 'read:askers/bpay-debt',
  sendAskersBpayDebt: 'send:askers/bpay-debt',
  readAskersFeedback: 'read:askers/feedback',
  readAskersOutstandingDebt: 'read:askers/outstanding-debt',
  sendAskersOutstandingDebt: 'send:askers/outstanding-debt',
  readAskersDoneFirstTask: 'read:askers/done-first-task',
  sendAskersSurvey: 'send:askers/survey',
  writeAskersSurvey: 'write:askers/survey',
  readAskersSurvey: 'read:askers/survey',
  readTaskerSearch: 'read:tasker/search',
  readTaskerPremium: 'read:tasker/premium',
  readTaskerInfo: 'read:tasker/info',
  writeTaskerStatus: 'write:tasker/status',
  writeTaskerEdit: 'write:tasker/edit',
  writeTaskerPremium: 'write:tasker/premium',
  readTaskerNotes: 'read:tasker/notes',
  writeTaskerNotes: 'write:tasker/notes',
  readTaskerSupportHistory: 'read:tasker/support-history',
  writeTaskerDelete: 'write:tasker/delete',
  readTaskerToTheTask: 'read:tasker/search-tasker-to-the-task',
  readAskerHasLowRatingTask: 'read:asker/asker-has-low-rating-task',

  readTaskerServices: 'read:tasker/services',
  readTaskersByStatus: 'read:taskers/read-by-status',
  readTaskersBirthday: 'read:taskers/read-by-birthday',
  readTaskersReceiveMonthlyReward: 'read:taskers/receive-monthly-reward',
  readTaskersNoMonthlyReward: 'read:taskers/no-monthly-reward',
  readTaskersInactive: 'read:taskers/inactive',
  readTaskersLowBalance: 'read:taskers/low-balance',
  readTaskersByTaskDone: 'read:taskers/read-by-task-done',
  readTaskersOnboardingList: 'read:taskers/onboarding',
  readTaskersTopup: 'read:taskers/top-up',

  readTaskersWorkingTime: 'read:taskers/working-time',
  writeTaskerServices: 'write:tasker/services',
  readTaskerTaskHistory: 'read:tasker/task-history',
  readTaskerTodoTask: 'read:tasker/todo-task',
  readTaskerCalendar: 'read:tasker/calendar',
  readTaskerLockedHistory: 'read:tasker/locked-history',
  readTaskerLockedCancelTask: 'read:tasker/locked-cancel-task',
  readTaskerCancelTaskHistory: 'read:tasker/cancel-task-history',
  readTaskerFinanceTransaction: 'read:tasker/finance-transaction',
  readTaskerQuickPostedTask: 'read:tasker/quick-posted-task',
  readTaskerViewedTask: 'read:tasker/viewed-task',
  readTaskerCity: 'read:tasker/city',
  writeTaskerCity: 'write:tasker/city',
  WRITE_TASKER_BANK_ACCOUNT: 'write:tasker/bank-account',
  readTaskerReportSearch: 'read:tasker-report/search',
  readTaskerLowRatingSearch: 'read:tasker-low-rating/search',
  readTaskerRegisterSearch: 'read:tasker-register/search',
  readTaskerOpenAppHistory: 'read:tasker/open-app-history',
  readTaskerReferralHistory: 'read:tasker/referral-history',
  writeTaskerFine: 'write:tasker/fine',
  writeTaskerCompensation: 'write:tasker/compensation',
  readTaskerViolate: 'read:tasker/violate',
  writeTaskerViolate: 'write:tasker/violate',
  readTaskerTraining: 'read:tasker/training',
  writeTaskerTraining: 'write:tasker/training',
  readTaskerFavouritedAsker: 'read:tasker/favourited-asker',
  readTaskerQAList: 'read:tasker/qa-list',
  readTaskerLeakage: 'read:tasker/leakage',
  readTaskerTrainingQuizzes: 'read:tasker/training-quizzes',
  writeTaskerTrainingQuizzes: 'write:tasker/training-quizzes',
  readTaskerHaveTaskInDay: 'read:tasker-have-task-in-day/list',
  readTaskerFeedback: 'read:askers/feedback',
  TASKER_BREWARD_LIST: 'read:tasker/breward',
  TASKER_WRITE_BREWARD: 'write:tasker/breward',
  READ_TASKER_CAMPAIGN: 'read:tasker/campaign',
  WRITE_TASKER_CAMPAIGN: 'write:tasker/campaign',
  readTaskerJourney: 'read:tasker/journey',
  writeTaskerJourney: 'write:tasker/journey',
  READ_TASKER_NEEDS_SUPPORT_REGISTRATION:
    'read:tasker/need-support-registration',

  readTaskSchedulesSearch: 'read:task-schedules/search',
  readTaskScheduleDetail: 'read:task-schedule/detail',
  writeTaskScheduleStop: 'write:task-schedule/stop',
  writeTaskScheduleCancel: 'write:task-schedule/cancel',
  writeTaskScheduleActive: 'write:task-schedule/active',
  writeTaskScheduleUpdateTasker: 'write:task-schedule/update-tasker',
  writeTaskScheduleDetail: 'write:task-schedule/detail',
  writeTaskScheduleNote: 'write:schedule/note',
  readTaskSpecialListSearch: 'read:task-special-list/search',
  writeTaskSpecialListSearch: 'write:task-special-list/search',
  readTaskReportSearch: 'read:task-report/search',
  readTaskCanceledSearch: 'read:task-canceled/search',
  readTaskUsePromotionCode: 'read:task-use-promotion-code/get-list',
  readSubscriptionSearch: 'read:subscription/search',
  sendSubscriptionSendOrderEmail: 'send:subscription/send-order-email',
  sendSubscriptionSendNotification: 'send:subscription/send-notification',
  sendSubscriptionSendReceipt: 'send:subscription/send-receipt',
  sendSubscriptionSendRenew: 'send:subscription/send-renew',
  readSubscriptionNote: 'read:subscription/note',
  writeSubscriptionNote: 'write:subscription/note',
  readSubscriptionDetail: 'read:subscription/detail',
  writeSubscriptionDetail: 'write:subscription/detail',
  writeSubscriptionCancel: 'write:subscription/cancel',
  writeSubscriptionRenew: 'write:subscription/renew',
  readSubscriptionTasker: 'read:subscription/tasker',
  writeSubscriptionTasker: 'write:subscription/tasker',
  readSubscriptionPurchaseOrder: 'read:subscription/purchase-order',
  writeSubscriptionPayPurchaseOrder: 'write:subscription/pay-purchase-order',

  readUserOtp: 'read:user-otp',
  writeNumberResentOtp: 'write:reset-number-resent-otp',
  call: 'call',
  writeTaskerDepositNewTasker: 'write:tasker/deposit-new-tasker',
  userManagement: 'user-management',
  teamManagement: 'team-management',

  // NOTIFICATION
  writeNotificationSendTasker: 'write:notification/send-tasker',
  writeNotificationSendAsker: 'read:notification/send-asker',
  readNotificationList: 'read:notification/list',
  readNotificationHistory: 'read:notification/history',
  writeNotificationCreate: 'write:notification/create',
  writeNotificationUpdate: 'write:notification/update',

  // COMPANY
  readCompany: 'read:company/list',
  writeCompanyCreate: 'write:company/create',
  writeCompanyUpdate: 'write:company/update',

  // STORE
  readGrocery: 'read:grocery/list',
  writeGroceryCreate: 'write:grocery/create',
  writeGroceryUpdate: 'write:grocery/update',

  // MARKETING
  readPromotion: 'read:promotion/list',
  readAskerPromotion: 'read:asker/promotion-list',
  writeSinglePromotion: 'write:promotion/create-single',
  writeSeriesPromotion: 'write:promotion/create-series',
  ASKER_WRITE_BREWARD: 'write:promotion/create-brewards',
  writeCampaign: 'write:promotion/create-campaign',
  writeComboVoucher: 'write:promotion/write-combo-voucher',

  // GIFT INFO
  readGiftCategory: 'read:gift-info/list',
  writeGiftCategory: 'write:gift-info/write-category',

  // CHANGE BACKEND USER
  writeBackendUserCountry: 'write:backend-user/change-country',

  // ============================= ACCOUNTING =============================
  readPageAccounting: 'read:accounting',
  readBtaskeeEmployees: 'read:accounting/btaskeeEmployees',
  writeBtaskeeEmployees: 'write:accounting/btaskeeEmployees',
  readRefundTransaction: 'read:accounting/refund-transaction',
  writeOutstandingPaymentPay: 'write:accounting/outstanding-payment-pay',
  readReportDailyIncome: 'read:accounting/report-daily-income',
  writeTaskerWithdraw: 'write:tasker/withdraw',
  writeTaskerDeposit: 'write:tasker/deposit',
  readTaskerWithdraw: 'read:tasker/withdraw',
  readTaskerDeposit: 'read:tasker/deposit',
  readPayoutOfTasker: 'read:accounting/read-payout-of-tasker',
  writePayoutOfTasker: 'write:accounting/write-payout-of-tasker',
  writeRepayoutOfTasker: 'write:accounting/write-repayout-of-tasker',
  readAccountingSpendingMonthlyReport:
    'read:accounting/read-spending-monthly-report',
  accountingCheckingExcel: 'accounting/checking-excel',
  accountingReadCardTransaction: 'accounting/read-card-transaction',
  accountingReadPaymentTransaction: 'accounting/read-payment-transaction',

  // ============================= TASK =============================
  readTaskSearch: 'read:task/search',
  readTaskGeneralInfo: 'read:task/general-info',
  writeTaskRequiredTools: 'write:task/required-tools',
  writeTaskSendNotification: 'write:task/send-notification',
  writeTaskSetCancelTask: 'write:task/set-cancel-task',
  writeTaskSetExpiredTask: 'write:task/set-expired-task',
  writeTaskSetDate: 'write:task/set-date',
  writeTaskSetDuration: 'write:task/set-duration',
  readTaskNote: 'read:task/note',
  readTaskViewedTasker: 'read:task/viewed-tasker',
  readTaskAcceptedTasker: 'read:task/accepted-tasker',
  readTaskConversation: 'read:task/conversation',
  readTaskSuportAskerTasker: 'read:task/suport-asker-tasker',
  readTaskRecommendTasker: 'read:task/recommend-tasker',
  readTaskCancelHistory: 'read:task/cancel-history',
  readTaskTaskerBlacklist: 'read:task/tasker-blacklist',
  writeTaskTaskerBlacklist: 'write:task/tasker-blacklist',
  readTaskChangesHistory: 'read:task/changes-history',
  writeTaskCreateSchedule: 'write:task/create-schedule',
  writeTaskCreateSubscription: 'write:task/create-subscription',
  writeTaskSupportAskerTasker: 'write:task/support-asker-tasker',
  writeTaskPromotion: 'write:task/promotion',
  readTaskPromotion: 'read:task/promotion',
  writeTaskNote: 'write:task/note',
  readTaskPaymentCardHistory: 'read:task/payment-card-history',
  writeTaskChangeAsker: 'write:task/write-task-change-asker',
  writeTaskFineAsker: 'write:task/fine-asker',
  writeTaskFineTasker: 'write:task/fine-tasker',
  readTaskCompensationList: 'read:task/compensation-list',
  readTaskPenaltyList: 'read:task/penalty-list',
  readTaskRefundRequest: 'read:task/refund',
  writeTaskRefundRequest: 'write:task/refund',
  writeTaskCreateRefundRequest: 'write:task/create-refund-request',
  writeTaskChangeToPosted: 'write:task/change-to-posted',
  sendTaskSendReceiptEmail: 'send:task/send-receipt-email',
  writeTaskSetAddress: 'write:task/set-address',
  writeTaskSetPaymentMethod: 'write:task/set-payment-method',
  writeTaskRating: 'write:task/rating',
  writeTaskAcceptTasker: 'write:task/accept-tasker',
  writeTaskDetail: 'write:task/update-task-detail',

  // ============================= REPORT =============================
  readReportTaskerActiveInDistrict: 'read:report/tasker-active-in-district',
  readReportLowRating: 'read:report/low-rating',
  readReportSupport: 'read:report/support',
  readReportSubscription: 'read:report/subscription',
  readReportOutstanding: 'read:report/outstanding',
  readReportTaskByDistrict: 'read:report/task-by-district',
  readReportUsagePromotion: 'read:report/usage-promotion',
  readReportBlacklistAsker: 'read:report/blacklist-asker',
  readReportSchedule: 'read:report/schedule',
  readReportRatingAsker: 'read:report/rating-asker',
  readReportPricing: 'read:report/pricing',
  readReportTaskByService: 'read:report/task-by-service',
  readReportCancelTask: 'read:report/cancel-task',
  readReportAskerReport: 'read:report/asker-report',
  readReportAskerInactive: 'read:report/asker-inactive',
  readReportSuspectTaskerReward: 'read:report/suspect-tasker-reward',
  readReportTaskStatistic: 'read:report/statistic-task',
  readReportTaskRating: 'read:report/task-rating',
  readTaskerOperationReport: 'read:tasker/operation-report',
  readTaskerGroupsManagementReport: 'read:tasker/groups-management-report',

  managerEmployee: 'manager-employee',

  USERS_DELETED_GET_LIST: 'read:users_deleted/get-list',
  USERS_DELETED_REVERT: 'write:users_deleted/revert',
  USERS_CAR_ADVERTISING_LIST: 'read:users-car-advertising/get-list',
  readAskerFinancialAccount: 'read:accounting/asker-financial-account',
  readTaskerFinancialAccount: 'read:accounting/tasker-financial-account',

  readTaskerProfile: 'read:tasker/tasker-profile',
  writeTaskerProfile: 'write:tasker/tasker-profile',

  READ_VAT_REQUEST: 'read:accounting/vat-request',
  READ_NOTIFICATION_HISTORY_IN_TASKER_DETAIL:
    'read:tasker/notification-history',
  WRITE_REDEEM_GIFT: 'write:tasker/redeem-gift',
  READ_TASKER_SUPPORT_GAS: 'read:tasker-report/support-gas',
  READ_TASKER_CANCELLATION_FEE: 'read:tasker-report/cancellation-fee',
  READ_TASKER_REFERRAL_MONEY: 'read:tasker-report/referral-money',
  READ_EXPORT_REPORT_SUPPORT_GAS: 'read&export:tasker-report/support-gas',
  READ_EXPORT_REPORT_CANCELLATION_FEE:
    'read&export:tasker-report/cancellation-fee',
  READ_EXPORT_REPORT_REFERRAL_MONEY: 'read&export:tasker-report/referral-money',
  WRITE_TASK_DETAIL: 'write:task/detail',
  READ_HISTORY_PAYOUT_TO_TASKER: 'read:accounting/history-payout-to-tasker',
  READ_ASKER_FLASH_SALE: 'read:asker/flash-sale',
  WRITE_ASKER_FLASH_SALE: 'write:asker/flash-sale',
  TASKER_READ_BPOINT_HISTORY: 'read:tasker/bpoint-history',

  TASKER_READ_TRAINING_JOURNEY: 'read:tasker/read-training-journey',
  TASKER_WRITE_TRAINING_JOURNEY: 'write:tasker/write-training-journey',
  READ_ASKER_REFERRAL_CAMPAIGN: 'read:asker/referral-campaign',
  WRITE_ASKER_REFERRAL_CAMPAIGN: 'write:asker/referral-campaign',
  READ_PAYMENT_CARD: 'read:asker/payment-card',
  WRITE_PAYMENT_CARD: 'write:asker/payment-card',
  READ_LEVEL_JOURNEY: 'read:setting/level-journey',

  READ_ACCOUNTING_REPORT_ASKER_INCOME: 'read:accounting-report/asker-income',
  READ_ACCOUNTING_REPORT_TASKER_INCOME: 'read:accounting-report/tasker-income',
  READ_ACCOUNTING_REPORT_ASKER_INCOME_TOP_UP:
    'read:accounting-report/asker-income/top-up',
  READ_ACCOUNTING_REPORT_ASKER_INCOME_REFUND:
    'read:accounting-report/asker-income/refund',
  READ_ACCOUNTING_REPORT_ASKER_INCOME_COMPENSATION:
    'read:accounting-report/asker-income/compensation',
  READ_ACCOUNTING_REPORT_TASKER_INCOME_BONUS:
    'read:accounting-report/tasker-income/bonus',
  READ_ACCOUNTING_REPORT_TASKER_INCOME_COMPENSATE:
    'read:accounting-report/tasker-income/compensate',
  READ_ACCOUNTING_REPORT_TASKER_INCOME_NEW_TASKER_TRIAL:
    'read:accounting-report/read-tasker-new-tasker-trial-income-report',
  READ_ACCOUNTING_REPORT_TASKER_INCOME_SERVICE_PAYMENT:
    'read:accounting-report/tasker-income/service-payment',
  READ_ACCOUNTING_REPORT_TASKER_INCOME_SUPPORT:
    'read:accounting-report/tasker-income/support',
  READ_ACCOUNTING_REPORT_TASKER_INCOME_TIP:
    'read:accounting-report/tasker-income/tip',
  READ_ACCOUNTING_REPORT_TASKER_INCOME_TOP_UP:
    'read:accounting-report/tasker-income/top-up',

  READ_ACCOUNTING_REPORT_ASKER_EXPENSE: 'read:accounting-report/asker-expense',
  READ_ACCOUNTING_REPORT_TASKER_EXPENSE:
    'read:accounting-report/tasker-expense',
  READ_ACCOUNTING_REPORT_ASKER_EXPENSE_PENALTY:
    'read:accounting-report/asker-expense/penalty',
  READ_ACCOUNTING_REPORT_ASKER_EXPENSE_SERVICE_PAYMENT:
    'read:accounting-report/asker-expense/service-payment',
  READ_ACCOUNTING_REPORT_ASKER_EXPENSE_TIP:
    'read:accounting-report/asker-expense/tip',
  READ_ACCOUNTING_REPORT_ASKER_EXPENSE_WITHDRAW:
    'read:accounting-report/asker-expense/withdraw',
  READ_ACCOUNTING_REPORT_TASKER_EXPENSE_PENALTY:
    'read:accounting-report/tasker-expense/penalty',
  READ_ACCOUNTING_REPORT_TASKER_EXPENSE_WITHDRAW:
    'read:accounting-report/tasker-expense/withdraw',

  READ_ACCOUNTING_REPORT_ASKER: 'read:accounting-report/asker',
  READ_ACCOUNTING_REPORT_TASKER: 'read:accounting-report/tasker',
  READ_ACCOUNTING_REPORT_ASKER_EMPLOYEE:
    'read:accounting-report/asker/employee',
  READ_ACCOUNTING_REPORT_ASKER_BANK_TRANSFER:
    'read:accounting-report/asker/bank-transfer',
  READ_ACCOUNTING_REPORT_ASKER_TOP_UP: 'read:accounting-report/asker/top-up',
  READ_ACCOUNTING_REPORT_ASKER_REFUND: 'read:accounting-report/asker/refund',
  READ_ACCOUNTING_REPORT_ASKER_COMPENSATION:
    'read:accounting-report/asker/compensation',
  READ_ACCOUNTING_REPORT_ASKER_SERVICE_PAYMENT:
    'read:accounting-report/asker/service-payment',
  READ_ACCOUNTING_REPORT_ASKER_PENALTY: 'read:accounting-report/asker/penalty',
  READ_ACCOUNTING_REPORT_ASKER_TIP: 'read:accounting-report/asker/tip',
  READ_ACCOUNTING_REPORT_TASKER_PENALTY:
    'read:accounting-report/tasker/penalty',
  READ_ACCOUNTING_REPORT_TASKER_BONUS: 'read:accounting-report/tasker/bonus',
  READ_ACCOUNTING_REPORT_TASKER_SERVICE_PAYMENT:
    'read:accounting-report/tasker/service-payment',
  READ_ACCOUNTING_REPORT_TASKER_COMPENSATION:
    'read:accounting-report/tasker/compensation',
  READ_ACCOUNTING_REPORT_TASKER_TIP: 'read:accounting-report/tasker/tip',
  READ_ACCOUNTING_REPORT_TASKER_SUPPORT:
    'read:accounting-report/tasker/support',
  READ_ACCOUNTING_REPORT_NEW_TASKER_TRIAL:
    'read:accounting-report/tasker/new-tasker-trial',
  READ_ACCOUNTING_REPORT_TASKER_TOP_UP: 'read:accounting-report/tasker/top-up',
  READ_ACCOUNTING_REPORT_TASKER_WITHDRAW:
    'read:accounting-report/tasker/withdraw',

  READ_REPORT_BREWARD: 'read:tasker-report/breward',
  READ_HISTORY_INCOME_REPORT: 'read:accounting/history-income-report',
  READ_TASKER_HAVE_TASK_NO_CHAT: 'read:tasker/have-task-no-chat',
};

export const ACCOUNTING_PERMISSION = [
  ACTION_PERMISSION_CONSTANTS.accountingCheckingExcel,
  ACTION_PERMISSION_CONSTANTS.accountingReadCardTransaction,
];
