export const REQUIRE_LENGTH_FOR_SEARCHING = 3;
export enum CHECKOUT_INPUT_TASKER_V3 {
  TASKER_INPUT = 'TASKER_INPUT',
  TASKER_OVERVIEW = 'TASKER_OVERVIEW',
  TASKER_QUALITY = 'TASKER_QUALITY',
}

export enum USER_TYPE {
  ASKER = 'ASKER',
  TASKER = 'TASKER',
}

export const SOURCE_NAME_FA_TRANSACTION = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  SYSTEM: 'SYSTEM',
};

export enum PAYOUT_STATUS {
  WAIT = 'WAIT',
  PAID = 'PAID',
}

export const QUIZZES_TYPE = {
  QUIZ: 'QUIZ',
  VIDEO: 'VIDEO',
};

export const FROM_BACKEND_OPTION = 'BACKEND';
export const TYPE_TASKER_TRAINING = {
  TRAINING_INPUT: 'TRAINING_INPUT',
  TRAINING_QUALITY: 'TRAINING_QUALITY',
  TRAINING_REGULATIONS: 'TRAINING_REGULATIONS',
  TRAINING_BASIC: 'TRAINING_BASIC',
  TRAINING_ADVANCED: 'TRAINING_ADVANCED',
};
export const PAYMENT_METHOD = {
  CASH: 'CASH',
  CREDIT: 'CREDIT',
  CARD: 'CARD',
  MOMO: 'MOMO',
  ZALO_PAY: 'ZALO_PAY',
  SHOPEE_PAY: 'SHOPEE_PAY',
  TRUE_MONEY: 'TRUE_MONEY',
  PROMPT_PAY: 'PROMPT_PAY',
  BANK_TRANSFER: 'BANK_TRANSFER',
  VN_PAY: 'VN_PAY',
  TIKI: 'TIKI',
  GO_PAY: 'GO_PAY',
  QRIS: 'QRIS',
  DANA: 'DANA',
};

export const PAYMENT_STATUS = {
  PAID: 'PAID',
  NEW: 'NEW',
  ERROR: 'ERROR',
  SENDING: 'SENDING',
  CHARGING: 'CHARGING',
  RESPONSED: 'RESPONSED',
  AUTHORISED: '3DAUTHORISED',
  CANCELED: 'CANCELED',
  FAILED: 'FAILED',
};

export const TASKER_NEEDS_SUPPORT_REGISTRATION = {
  INPUT_OTP: 'INPUT_OTP',
  SELECT_PLACES_AND_SERVICES: 'SELECT_PLACES_AND_SERVICES',
  TRAINING: 'TRAINING',
  SEND_PROFILE: 'SEND_PROFILE',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  INACTIVE: 'INACTIVE',
  IN_PROBATION: 'IN_PROBATION',
  LOCKED: 'LOCKED',
  UNVERIFIED: 'UNVERIFIED',
  UNLOCKED: 'UNLOCKED',
};

export const CHECK_INPUT_TYPE_OF_TASKER = {
  TASKER_PASS: 'TASKER_PASS',
};

export const CLEVEL_TAP_API_STATUS = {
  SUCCESS: 'success',
  FAIL: 'fail',
};

export enum KEY_CHANGE_HISTORY_USER {
  UPDATE_BANK_ACCOUNT_NUMBER = 'UPDATE_BANK_ACCOUNT_NUMBER',
}
export const NORMAL_NOTIFICATION_FROM_BACKEND = 25;
